---
- include: headless.yml

- name: Provision desktop system
  hosts: all
  roles:
    - i3
    - fonts
    - home
    - touchpad
    - clipboard
    - gtk
    - icons
    - pulseaudio
    - termite
    - yubikey
    - gopass
    - cloudprint
    - dropbox
    - chrome
    - firefox
    - wavebox
    - hangouts
    - skype
    - qalculate
    - insomnia
    - vpn
    - flux
    - vagrant
    - android
    - spotify
    - ardour
    - gimp
    - zathura
